
GET http://localhost:8080/api/playlists/

###

GET http://localhost:8080/api/playlists/add/

###
POST http://localhost:8080/api/playlists/add
Content-Type: application/x-www-form-urlencoded

name=playlist name
